<?php 
require_once("conn.php");
$a = array(
												array("AF","Afghanistan"),
                                                array("AL","Albania"),
                                                array("DZ","Algeria"),
                                                array("AS","American Samoa"),
                                                array("AD","Andorra"),
                                                array("AO","Angola"),
                                                array("AI","Anguilla"),
                                                array("AR","Argentina"),
                                                array("AM","Armenia"),
                                                array("AW","Aruba"),
                                                array("AU","Australia"),
                                                array("AT","Austria"),
                                                array("AZ","Azerbaijan"),
                                                array("BS","Bahamas"),
                                                array("BH","Bahrain"),
                                                array("BD","Bangladesh"),
                                                array("BB","Barbados"),
                                                array("BY","Belarus"),
                                                array("BE","Belgium"),
                                                array("BZ","Belize"),
                                                array("BJ","Benin"),
                                                array("BM","Bermuda"),
                                                array("BT","Bhutan"),
                                                array("BO","Bolivia"),
                                                array("BA","Bosnia and Herzegowina"),
                                                array("BW","Botswana"),
                                                array("BV","Bouvet Island"),
                                                array("BR","Brazil"),
                                                array("IO","British Indian Ocean Territory"),
                                                array("BN","Brunei Darussalam"),
                                                array("BG","Bulgaria"),
                                                array("BF","Burkina Faso"),
                                                array("BI","Burundi"),
                                                array("KH","Cambodia"),
                                                array("CM","Cameroon"),
                                                array("CA","Canada"),
                                                array("CV","Cape Verde"),
                                                array("KY","Cayman Islands"),
                                                array("CF","Central African Republic"),
                                                array("TD","Chad"),
                                                array("CL","Chile"),
                                                array("CN","China"),
                                                array("CX","Christmas Island"),
                                                array("CC","Cocos (Keeling) Islands"),
                                                array("CO","Colombia"),
                                                array("KM","Comoros"),
                                                array("CG","Congo"),
                                                array("CD","Congo, the Democratic Republic of the"),
                                                array("CK","Cook Islands"),
                                                array("CR","Costa Rica"),
                                                array("CI","Cote d'Ivoire"),
                                                array("HR","Croatia (Hrvatska)"),
                                                array("CU","Cuba"),
                                                array("CY","Cyprus"),
                                                array("CZ","Czech Republic"),
                                                array("DK","Denmark"),
                                                array("DJ","Djibouti"),
                                                array("DM","Dominica"),
                                                array("DO","Dominican Republic"),
                                                array("EC","Ecuador"),
                                                array("EG","Egypt"),
                                                array("SV","El Salvador"),
                                                array("GQ","Equatorial Guinea"),
                                                array("ER","Eritrea"),
                                                array("EE","Estonia"),
                                                array("ET","Ethiopia"),
                                                array("FK","Falkland Islands (Malvinas)"),
                                                array("FO","Faroe Islands"),
                                                array("FJ","Fiji"),
                                                array("FI","Finland"),
                                                array("FR","France"),
                                                array("GF","French Guiana"),
                                                array("PF","French Polynesia"),
                                                array("TF","French Southern Territories"),
                                                array("GA","Gabon"),
                                                array("GM","Gambia"),
                                                array("GE","Georgia"),
                                                array("DE","Germany"),
                                                array("GH","Ghana"),
                                                array("GI","Gibraltar"),
                                                array("GR","Greece"),
                                                array("GL","Greenland"),
                                                array("GD","Grenada"),
                                                array("GP","Guadeloupe"),
                                                array("GU","Guam"),
                                                array("GT","Guatemala"),
                                                array("GN","Guinea"),
                                                array("GW","Guinea-Bissau"),
                                                array("GY","Guyana"),
                                                array("HT","Haiti"),
                                                array("HM","Heard and Mc Donald Islands"),
                                                array("VA","Holy See (Vatican City State)"),
                                                array("HN","Honduras"),
                                                array("HK","Hong Kong"),
                                                array("HU","Hungary"),
                                                array("IS","Iceland"),
                                                array("IN","India"),
                                                array("ID","Indonesia"),
                                                array("IR","Iran (Islamic Republic of)"),
                                                array("IQ","Iraq"),
                                                array("IE","Ireland"),
                                                array("IL","Israel"),
                                                array("IT","Italy"),
                                                array("JM","Jamaica"),
                                                array("JP","Japan"),
                                                array("JO","Jordan"),
                                                array("KZ","Kazakhstan"),
                                                array("KE","Kenya"),
                                                array("KI","Kiribati"),
                                                array("KP","Korea, Democratic Peoples Republic of"),
                                                array("KR","Korea, Republic of"),
                                                array("KW","Kuwait"),
                                                array("KG","Kyrgyzstan"),
                                                array("LA","Lao Peoples Democratic Republic"),
                                                array("LV","Latvia"),
                                                array("LB","Lebanon"),
                                                array("LS","Lesotho"),
                                                array("LR","Liberia"),
                                                array("LY","Libyan Arab Jamahiriya"),
                                                array("LI","Liechtenstein"),
                                                array("LT","Lithuania"),
                                                array("LU","Luxembourg"),
                                                array("MO","Macau"),
                                                array("MK","Macedonia, The Former Yugoslav Republic of"),
                                                array("MG","Madagascar"),
                                                array("MW","Malawi"),
                                                array("MY","Malaysia"),
                                                array("MV","Maldives"),
                                                array("ML","Mali"),
                                                array("MT","Malta"),
                                                array("MH","Marshall Islands"),
                                                array("MQ","Martinique"),
                                                array("MR","Mauritania"),
                                                array("MU","Mauritius"),
                                                array("YT","Mayotte"),
                                                array("MX","Mexico"),
                                                array("FM","Micronesia, Federated States of"),
                                                array("MD","Moldova, Republic of"),
                                                array("MC","Monaco"),
                                                array("MN","Mongolia"),
                                                array("MS","Montserrat"),
                                                array("MA","Morocco"),
                                                array("MZ","Mozambique"),
                                                array("MM","Myanmar"),
                                                array("NA","Namibia"),
                                                array("NR","Nauru"),
                                                array("NP","Nepal"),
                                                array("NL","Netherlands"),
                                                array("AN","Netherlands Antilles"),
                                                array("NC","New Caledonia"),
                                                array("NZ","New Zealand"),
                                                array("NI","Nicaragua"),
                                                array("NE","Niger"),
                                                array("NG","Nigeria"),
                                                array("NU","Niue"),
                                                array("NF","Norfolk Island"),
                                                array("MP","Northern Mariana Islands"),
                                                array("NO","Norway"),
                                                array("OM","Oman"),
                                                array("PK","Pakistan"),
                                                array("PW","Palau"),
                                                array("PA","Panama"),
                                                array("PG","Papua New Guinea"),
                                                array("PY","Paraguay"),
                                                array("PE","Peru"),
                                                array("PH","Philippines"),
                                                array("PN","Pitcairn"),
                                                array("PL","Poland"),
                                                array("PT","Portugal"),
                                                array("PR","Puerto Rico"),
                                                array("QA","Qatar"),
                                                array("RE","Reunion"),
                                                array("RO","Romania"),
                                                array("RU","Russian Federation"),
                                                array("RW","Rwanda"),
                                                array("KN","Saint Kitts and Nevis"),
                                                array("LC","Saint LUCIA"),
                                                array("VC","Saint Vincent and the Grenadines"),
                                                array("WS","Samoa"),
                                                array("SM","San Marino"),
                                                array("ST","Sao Tome and Principe"),
                                                array("SA","Saudi Arabia"),
                                                array("SN","Senegal"),
                                                array("SC","Seychelles"),
                                                array("SL","Sierra Leone"),
                                                array("SG","Singapore"),
                                                array("SK","Slovakia (Slovak Republic)"),
                                                array("SI","Slovenia"),
                                                array("SB","Solomon Islands"),
                                                array("SO","Somalia"),
                                                array("ZA","South Africa"),
                                                array("GS","South Georgia and the South Sandwich Islands"),
                                                array("ES","Spain"),
                                                array("LK","Sri Lanka"),
                                                array("SH","St. Helena"),
                                                array("PM","St. Pierre and Miquelon"),
                                                array("SD","Sudan"),
                                                array("SR","Suriname"),
                                                array("SJ","Svalbard and Jan Mayen Islands"),
                                                array("SZ","Swaziland"),
                                                array("SE","Sweden"),
                                                array("CH","Switzerland"),
                                                array("SY","Syrian Arab Republic"),
                                                array("TW","Taiwan, Province of China"),
                                                array("TJ","Tajikistan"),
                                                array("TZ","Tanzania, United Republic of"),
                                                array("TH","Thailand"),
                                                array("TG","Togo"),
                                                array("TK","Tokelau"),
                                                array("TO","Tonga"),
                                                array("TT","Trinidad and Tobago"),
                                                array("TN","Tunisia"),
                                                array("TR","Turkey"),
                                                array("TM","Turkmenistan"),
                                                array("TC","Turks and Caicos Islands"),
                                                array("TV","Tuvalu"),
                                                array("UG","Uganda"),
                                                array("UA","Ukraine"),
                                                array("AE","United Arab Emirates"),
                                                array("GB","United Kingdom"),
                                                array("US","United States"),
                                                array("UM","United States Minor Outlying Islands"),
                                                array("UY","Uruguay"),
                                                array("UZ","Uzbekistan"),
                                                array("VU","Vanuatu"),
                                                array("VE","Venezuela"),
                                                array("VN","Viet Nam"),
                                                array("VG","Virgin Islands (British)"),
                                                array("VI","Virgin Islands (U.S.)"),
                                                array("WF","Wallis and Futuna Islands"),
                                                array("EH","Western Sahara"),
                                                array("YE","Yemen"),
                                                array("ZM","Zambia"),
                                                array("ZW","Zimbabwe")
);

$i = 0;
while($res =  $a){
	
    $code = $a[$i][0];
	$name = $a[$i][1];
	if($code){
	//$qry = mysql_query("insert into `country` (`country_code`,`country_name`) values('".$code."','".$name."')  ");
	}
	$i++;
}
?>